name: Run app.py

on:
  schedule:
    - cron: '0 9 * * *' # At 09:00 every day
  workflow_dispatch: # Add workflow_dispatch to manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CELL_NUMBER: ${{ secrets.CELL_NUMBER }}
      GMAIL: ${{ secrets.GMAIL }}
      GMAIL_APP_PASS: ${{ secrets.GMAIL_APP_PASS }}
      PROVIDER: ${{ secrets.PROVIDER }}
      SHEETY_API_KEY: ${{ secrets.SHEETY_API_KEY }}
      SHEETY_SPREADSHEET: ${{ secrets.SHEETY_SPREADSHEET }}
      TEQUILA_API_KEY: ${{ secrets.TEQUILA_API_KEY }}

    steps:
      - name: Print Environment Variables
        run: |
          echo "CELL_NUMBER=${CELL_NUMBER}"
          echo "GMAIL=${GMAIL}"
          echo "GMAIL_APP_PASS=${GMAIL_APP_PASS}"
          echo "PROVIDER=${PROVIDER}"
          echo "SHEETY_API_KEY=${SHEETY_API_KEY}"
          echo "SHEETY_SPREADSHEET=${SHEETY_SPREADSHEET}"
          echo "TEQUILA_API_KEY=${TEQUILA_API_KEY}"

      - name: Checkout repo content
        uses: actions/checkout@v2 # Checkout the repository content

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Install the Python version needed

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute py script # Run app.py
        run: |
          export SHEETY_API_KEY=${{ secrets.SHEETY_API_KEY }}
          export SHEETY_SPREADSHEET=${{ secrets.SHEETY_SPREADSHEET }}
          python main.py
